# Generated by Django 5.0 on 2026-01-02 07:29

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('partner_code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('business_name', models.CharField(max_length=255)),
                ('business_type', models.CharField(choices=[('individual', 'Individual'), ('company', 'Company/Shop'), ('franchise', 'Franchise')], default='individual', max_length=20)),
                ('business_registration_number', models.CharField(blank=True, max_length=100)),
                ('tax_id', models.CharField(blank=True, max_length=50)),
                ('contact_person', models.CharField(max_length=255)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_phone', models.CharField(max_length=20)),
                ('alternate_phone', models.CharField(blank=True, max_length=20)),
                ('address_line1', models.CharField(max_length=255)),
                ('address_line2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=10)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('service_radius', models.DecimalField(decimal_places=2, default=Decimal('5.00'), help_text='Service radius in kilometers', max_digits=5)),
                ('daily_capacity', models.IntegerField(default=50, help_text='Maximum orders per day', validators=[django.core.validators.MinValueValidator(1)])),
                ('current_load', models.IntegerField(default=0, help_text='Current active orders', validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20)),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('average_rating', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=3, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('5.00'))])),
                ('total_ratings', models.IntegerField(default=0)),
                ('completed_orders', models.IntegerField(default=0)),
                ('cancelled_orders', models.IntegerField(default=0)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('commission_rate', models.DecimalField(decimal_places=2, default=Decimal('15.00'), help_text='Commission percentage', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('bank_name', models.CharField(blank=True, max_length=100)),
                ('account_holder_name', models.CharField(blank=True, max_length=255)),
                ('account_number', models.CharField(blank=True, max_length=50)),
                ('ifsc_code', models.CharField(blank=True, max_length=20)),
                ('upi_id', models.CharField(blank=True, max_length=100)),
                ('business_license', models.FileField(blank=True, upload_to='partners/documents/')),
                ('tax_certificate', models.FileField(blank=True, upload_to='partners/documents/')),
                ('id_proof', models.FileField(blank=True, upload_to='partners/documents/')),
                ('description', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True, help_text='Internal notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('onboarded_at', models.DateTimeField(blank=True, null=True)),
                ('pricing_zone', models.ForeignKey(default='A', on_delete=django.db.models.deletion.PROTECT, related_name='partners', to='services.pricingzone')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='partner_profile', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_partners', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Partner',
                'verbose_name_plural': 'Partners',
                'db_table': 'partners',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PartnerAvailability',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('weekday', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('is_available', models.BooleanField(default=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability', to='partners.partner')),
            ],
            options={
                'verbose_name': 'Partner Availability',
                'verbose_name_plural': 'Partner Availability',
                'db_table': 'partner_availability',
                'ordering': ['weekday', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='PartnerHoliday',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('reason', models.CharField(max_length=255)),
                ('is_recurring', models.BooleanField(default=False, help_text='Recurs annually')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holidays', to='partners.partner')),
            ],
            options={
                'verbose_name': 'Partner Holiday',
                'verbose_name_plural': 'Partner Holidays',
                'db_table': 'partner_holidays',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='PartnerPerformance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('month', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('year', models.IntegerField()),
                ('total_orders', models.IntegerField(default=0)),
                ('completed_orders', models.IntegerField(default=0)),
                ('cancelled_orders', models.IntegerField(default=0)),
                ('rejected_orders', models.IntegerField(default=0)),
                ('gross_revenue', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('commission_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('net_revenue', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('average_rating', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=3)),
                ('on_time_delivery_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Percentage', max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_metrics', to='partners.partner')),
            ],
            options={
                'verbose_name': 'Partner Performance',
                'verbose_name_plural': 'Partner Performance Metrics',
                'db_table': 'partner_performance',
                'ordering': ['-year', '-month'],
            },
        ),
        migrations.CreateModel(
            name='PartnerServiceArea',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pincode', models.CharField(max_length=10)),
                ('area_name', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('extra_delivery_charge', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_areas', to='partners.partner')),
            ],
            options={
                'verbose_name': 'Partner Service Area',
                'verbose_name_plural': 'Partner Service Areas',
                'db_table': 'partner_service_areas',
            },
        ),
        migrations.AddIndex(
            model_name='partner',
            index=models.Index(fields=['partner_code'], name='partners_partner_9f6e03_idx'),
        ),
        migrations.AddIndex(
            model_name='partner',
            index=models.Index(fields=['status', '-created_at'], name='partners_status_2c7dd1_idx'),
        ),
        migrations.AddIndex(
            model_name='partner',
            index=models.Index(fields=['city', 'status'], name='partners_city_8f09fe_idx'),
        ),
        migrations.AddIndex(
            model_name='partner',
            index=models.Index(fields=['pincode'], name='partners_pincode_740963_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='partneravailability',
            unique_together={('partner', 'weekday')},
        ),
        migrations.AlterUniqueTogether(
            name='partnerperformance',
            unique_together={('partner', 'month', 'year')},
        ),
        migrations.AddIndex(
            model_name='partnerservicearea',
            index=models.Index(fields=['pincode', 'is_active'], name='partner_ser_pincode_874cc0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='partnerservicearea',
            unique_together={('partner', 'pincode')},
        ),
    ]
