# Generated by Django 6.0 on 2026-01-03 11:27

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0001_initial"),
        ("partners", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="assigned_partner_id",
        ),
        migrations.AddField(
            model_name="order",
            name="assigned_partner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_orders",
                to="partners.partner",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="partner_accepted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="partner_rejected_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="partner_rejection_reason",
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name="DeliveryProof",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("package_photos", models.JSONField(blank=True, default=list)),
                (
                    "delivery_location_photo",
                    models.CharField(blank=True, max_length=500),
                ),
                ("customer_signature", models.CharField(blank=True, max_length=500)),
                ("signature_name", models.CharField(blank=True, max_length=255)),
                ("delivered_to", models.CharField(blank=True, max_length=255)),
                ("delivered_to_relation", models.CharField(blank=True, max_length=100)),
                (
                    "delivery_latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "delivery_longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "delivered_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("delivery_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "delivered_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="deliveries_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delivery_proof",
                        to="orders.order",
                    ),
                ),
            ],
            options={
                "verbose_name": "Delivery Proof",
                "verbose_name_plural": "Delivery Proofs",
                "db_table": "delivery_proofs",
            },
        ),
        migrations.CreateModel(
            name="OrderItemProcessing",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("inspecting", "Under Inspection"),
                            ("stain_treating", "Stain Treatment"),
                            ("washing", "Washing"),
                            ("drying", "Drying"),
                            ("ironing", "Ironing"),
                            ("quality_check", "Quality Check"),
                            ("packaged", "Packaged"),
                            ("completed", "Completed"),
                            ("damaged", "Damaged"),
                            ("lost", "Lost"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "initial_condition",
                    models.CharField(
                        choices=[
                            ("excellent", "Excellent"),
                            ("good", "Good"),
                            ("fair", "Fair - Minor Issues"),
                            ("poor", "Poor - Damaged"),
                            ("missing", "Missing/Lost"),
                        ],
                        default="good",
                        max_length=20,
                    ),
                ),
                (
                    "final_condition",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("excellent", "Excellent"),
                            ("good", "Good"),
                            ("fair", "Fair - Minor Issues"),
                            ("poor", "Poor - Damaged"),
                            ("missing", "Missing/Lost"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("has_stains", models.BooleanField(default=False)),
                ("stain_details", models.TextField(blank=True)),
                ("stain_photos", models.JSONField(blank=True, default=list)),
                ("has_damage", models.BooleanField(default=False)),
                ("damage_details", models.TextField(blank=True)),
                ("damage_photos", models.JSONField(blank=True, default=list)),
                ("requires_special_care", models.BooleanField(default=False)),
                ("special_care_notes", models.TextField(blank=True)),
                ("washing_temp", models.CharField(blank=True, max_length=20)),
                ("detergent_type", models.CharField(blank=True, max_length=50)),
                ("drying_method", models.CharField(blank=True, max_length=20)),
                ("ironing_temp", models.CharField(blank=True, max_length=20)),
                ("inspection_at", models.DateTimeField(blank=True, null=True)),
                ("washing_started_at", models.DateTimeField(blank=True, null=True)),
                ("washing_completed_at", models.DateTimeField(blank=True, null=True)),
                ("drying_started_at", models.DateTimeField(blank=True, null=True)),
                ("drying_completed_at", models.DateTimeField(blank=True, null=True)),
                ("ironing_started_at", models.DateTimeField(blank=True, null=True)),
                ("ironing_completed_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "quality_score",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                ("quality_notes", models.TextField(blank=True)),
                (
                    "additional_charges",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                ("additional_charges_reason", models.TextField(blank=True)),
                ("processing_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "order_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="processing_details",
                        to="orders.orderitem",
                    ),
                ),
                (
                    "processed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="processed_items",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Order Item Processing",
                "verbose_name_plural": "Order Item Processing",
                "db_table": "order_item_processing",
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(
                        fields=["order_item", "status"],
                        name="order_item__order_i_0542c9_idx",
                    ),
                    models.Index(
                        fields=["status", "created_at"],
                        name="order_item__status_968ecb_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="OrderProcessingStage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("assigned", "Assigned to Partner"),
                            ("accepted", "Accepted by Partner"),
                            ("rejected", "Rejected by Partner"),
                            ("pickup_scheduled", "Pickup Scheduled"),
                            ("out_for_pickup", "Out for Pickup"),
                            ("pickup_completed", "Pickup Completed"),
                            ("inspection", "Quality Inspection"),
                            ("inspection_complete", "Inspection Complete"),
                            ("stain_treatment", "Stain Treatment"),
                            ("washing", "Washing"),
                            ("drying", "Drying"),
                            ("ironing", "Ironing/Pressing"),
                            ("steam_pressing", "Steam Pressing"),
                            ("quality_check", "Quality Control Check"),
                            ("packaging", "Packaging"),
                            ("ready_for_delivery", "Ready for Delivery"),
                            ("out_for_delivery", "Out for Delivery"),
                            ("delivered", "Delivered to Customer"),
                            ("on_hold", "On Hold"),
                            ("issue_reported", "Issue Reported"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "stage_category",
                    models.CharField(
                        choices=[
                            ("assignment", "Assignment"),
                            ("pickup", "Pickup"),
                            ("inspection", "Inspection"),
                            ("processing", "Processing"),
                            ("finishing", "Finishing"),
                            ("delivery", "Delivery"),
                            ("issue", "Issue"),
                        ],
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("duration_minutes", models.IntegerField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("photos", models.JSONField(blank=True, default=list)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("has_issue", models.BooleanField(default=False)),
                ("issue_description", models.TextField(blank=True)),
                ("issue_resolved", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="processing_stages",
                        to="orders.order",
                    ),
                ),
                (
                    "performed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="performed_stages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Order Processing Stage",
                "verbose_name_plural": "Order Processing Stages",
                "db_table": "order_processing_stages",
                "ordering": ["started_at"],
                "indexes": [
                    models.Index(
                        fields=["order", "stage"], name="order_proce_order_i_0c2dde_idx"
                    ),
                    models.Index(
                        fields=["order", "started_at"],
                        name="order_proce_order_i_e14e72_idx",
                    ),
                    models.Index(
                        fields=["stage", "created_at"],
                        name="order_proce_stage_a1815d_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="PartnerOrderNote",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "note_type",
                    models.CharField(
                        choices=[
                            ("general", "General Note"),
                            ("issue", "Issue/Problem"),
                            ("customer_request", "Customer Request"),
                            ("internal", "Internal Communication"),
                            ("quality", "Quality Concern"),
                        ],
                        default="general",
                        max_length=30,
                    ),
                ),
                ("content", models.TextField()),
                ("attachments", models.JSONField(blank=True, default=list)),
                ("is_urgent", models.BooleanField(default=False)),
                ("is_resolved", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="partner_order_notes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="partner_notes",
                        to="orders.order",
                    ),
                ),
            ],
            options={
                "verbose_name": "Partner Order Note",
                "verbose_name_plural": "Partner Order Notes",
                "db_table": "partner_order_notes",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["order", "-created_at"],
                        name="partner_ord_order_i_05bbea_idx",
                    ),
                    models.Index(
                        fields=["is_urgent", "-created_at"],
                        name="partner_ord_is_urge_cf17c6_idx",
                    ),
                ],
            },
        ),
    ]
