# Generated by Django 6.0 on 2026-01-09 15:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentmethod",
            name="bank_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="paymentmethod",
            name="provider",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="paymentmethod",
            name="wallet_number",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="paymentmethod",
            name="wallet_provider",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="paymentmethod",
            name="type",
            field=models.CharField(
                choices=[
                    ("card", "Card"),
                    ("upi", "UPI"),
                    ("netbanking", "Net Banking"),
                    ("wallet", "Digital Wallet"),
                ],
                max_length=20,
            ),
        ),
    ]
