# Generated by Django 6.0 on 2026-01-03 15:42

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("orders", "0002_remove_order_assigned_partner_id_and_more"),
        ("partners", "0001_initial"),
        ("payments", "0001_initial"),
        ("services", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GarmentRecognition",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("image", models.ImageField(upload_to="garment_images/%Y/%m/%d/")),
                ("image_url", models.URLField(blank=True, max_length=500)),
                ("garment_type", models.CharField(max_length=100)),
                ("garment_category", models.CharField(max_length=50)),
                ("fabric_type", models.CharField(blank=True, max_length=100)),
                ("color_primary", models.CharField(blank=True, max_length=50)),
                ("color_secondary", models.CharField(blank=True, max_length=50)),
                ("has_stains", models.BooleanField(default=False)),
                ("stain_locations", models.JSONField(blank=True, default=list)),
                ("has_damages", models.BooleanField(default=False)),
                ("damage_details", models.JSONField(blank=True, default=list)),
                ("care_instructions", models.JSONField(blank=True, default=dict)),
                ("special_requirements", models.JSONField(blank=True, default=list)),
                (
                    "confidence_level",
                    models.CharField(
                        choices=[
                            ("high", "High (>80%)"),
                            ("medium", "Medium (50-80%)"),
                            ("low", "Low (<50%)"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                (
                    "confidence_score",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Confidence score from 0 to 100",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("model_version", models.CharField(default="v1.0", max_length=50)),
                (
                    "processing_time_ms",
                    models.IntegerField(help_text="Processing time in milliseconds"),
                ),
                ("raw_response", models.JSONField(blank=True, default=dict)),
                (
                    "estimated_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="AI-estimated service price",
                        max_digits=10,
                        null=True,
                    ),
                ),
                ("is_verified", models.BooleanField(default=False)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="garment_recognitions",
                        to="orders.order",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="garment_recognitions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_recognitions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Garment Recognition",
                "verbose_name_plural": "Garment Recognitions",
                "db_table": "garment_recognitions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MLModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "model_type",
                    models.CharField(
                        choices=[
                            ("garment_recognition", "Garment Recognition"),
                            ("price_estimation", "Price Estimation"),
                            ("demand_forecast", "Demand Forecasting"),
                            ("recommendation", "Recommendation Engine"),
                            ("fraud_detection", "Fraud Detection"),
                            ("chatbot", "Chatbot NLP"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                ("version", models.CharField(max_length=50, unique=True)),
                ("description", models.TextField()),
                ("framework", models.CharField(max_length=50)),
                ("algorithm", models.CharField(max_length=100)),
                ("hyperparameters", models.JSONField(blank=True, default=dict)),
                ("training_dataset_size", models.IntegerField(blank=True, null=True)),
                ("training_start_date", models.DateTimeField(blank=True, null=True)),
                ("training_end_date", models.DateTimeField(blank=True, null=True)),
                (
                    "training_duration_seconds",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "accuracy",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Model accuracy percentage",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "precision",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "recall",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "f1_score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "performance_metrics",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional performance metrics",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("training", "Training"),
                            ("testing", "Testing"),
                            ("staging", "Staging"),
                            ("production", "Production"),
                            ("deprecated", "Deprecated"),
                        ],
                        db_index=True,
                        default="training",
                        max_length=20,
                    ),
                ),
                ("deployed_at", models.DateTimeField(blank=True, null=True)),
                ("deployment_url", models.URLField(blank=True, max_length=500)),
                ("model_file_path", models.CharField(blank=True, max_length=500)),
                (
                    "model_file_size_mb",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("prediction_count", models.IntegerField(default=0)),
                (
                    "avg_inference_time_ms",
                    models.IntegerField(
                        blank=True,
                        help_text="Average inference time in milliseconds",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_models",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "ML Model",
                "verbose_name_plural": "ML Models",
                "db_table": "ml_models",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PriceEstimation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("garment_type", models.CharField(max_length=100)),
                ("fabric_type", models.CharField(blank=True, max_length=100)),
                ("service_type", models.CharField(max_length=50)),
                ("urgency_level", models.CharField(default="standard", max_length=20)),
                (
                    "current_demand_score",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("50.00"),
                        help_text="Demand score 0-100",
                        max_digits=5,
                    ),
                ),
                (
                    "competitor_avg_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "seasonal_factor",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("1.00"),
                        help_text="Seasonal multiplier (0.5 - 2.0)",
                        max_digits=5,
                    ),
                ),
                (
                    "location_lat",
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=10, null=True
                    ),
                ),
                (
                    "location_lng",
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=10, null=True
                    ),
                ),
                ("pricing_zone", models.CharField(blank=True, max_length=50)),
                ("base_price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "recommended_price",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("min_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("max_price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "profit_margin",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Estimated profit margin percentage",
                        max_digits=5,
                    ),
                ),
                (
                    "conversion_probability",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Probability of customer accepting this price (0-100)",
                        max_digits=5,
                    ),
                ),
                ("model_version", models.CharField(default="v1.0", max_length=50)),
                (
                    "confidence_score",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("features_used", models.JSONField(blank=True, default=dict)),
                (
                    "actual_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Actual price charged",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "was_accepted",
                    models.BooleanField(
                        blank=True,
                        help_text="Whether customer accepted the price",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "garment_recognition",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="price_estimations",
                        to="ai.garmentrecognition",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_estimations",
                        to="services.service",
                    ),
                ),
            ],
            options={
                "verbose_name": "Price Estimation",
                "verbose_name_plural": "Price Estimations",
                "db_table": "price_estimations",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Recommendation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "recommendation_type",
                    models.CharField(
                        choices=[
                            ("service", "Service Recommendation"),
                            ("addon", "Add-on Suggestion"),
                            ("upsell", "Upsell Opportunity"),
                            ("cross_sell", "Cross-sell Item"),
                            ("offer", "Personalized Offer"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "relevance_score",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="How relevant this recommendation is (0-100)",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "confidence_score",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("reason_code", models.CharField(max_length=50)),
                ("reason_description", models.TextField(blank=True)),
                (
                    "influencing_factors",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Factors that led to this recommendation",
                    ),
                ),
                ("similar_user_ids", models.JSONField(blank=True, default=list)),
                ("similar_order_ids", models.JSONField(blank=True, default=list)),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "estimated_savings",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("was_shown", models.BooleanField(default=False)),
                ("shown_at", models.DateTimeField(blank=True, null=True)),
                ("was_clicked", models.BooleanField(default=False)),
                ("clicked_at", models.DateTimeField(blank=True, null=True)),
                ("was_accepted", models.BooleanField(default=False)),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                ("model_version", models.CharField(default="v1.0", max_length=50)),
                (
                    "algorithm_used",
                    models.CharField(
                        default="collaborative_filtering",
                        help_text="Algorithm: collaborative_filtering, content_based, hybrid",
                        max_length=50,
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When this recommendation expires",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "addon",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_recommendations",
                        to="services.addon",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_recommendations",
                        to="orders.order",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_recommendations",
                        to="services.service",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_recommendations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "AI Recommendation",
                "verbose_name_plural": "AI Recommendations",
                "db_table": "ai_recommendations",
                "ordering": ["-relevance_score", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DemandForecast",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("forecast_date", models.DateField(db_index=True)),
                (
                    "forecast_hour",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(23),
                        ],
                    ),
                ),
                (
                    "granularity",
                    models.CharField(
                        choices=[
                            ("hourly", "Hourly"),
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                        ],
                        default="daily",
                        max_length=20,
                    ),
                ),
                ("service_area", models.CharField(blank=True, max_length=100)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("predicted_order_count", models.IntegerField()),
                (
                    "predicted_revenue",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "prediction_lower_bound",
                    models.IntegerField(
                        help_text="Lower bound of 95% confidence interval"
                    ),
                ),
                (
                    "prediction_upper_bound",
                    models.IntegerField(
                        help_text="Upper bound of 95% confidence interval"
                    ),
                ),
                (
                    "confidence_score",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "category_breakdown",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Predicted orders by service category",
                    ),
                ),
                ("is_holiday", models.BooleanField(default=False)),
                ("is_weekend", models.BooleanField(default=False)),
                ("weather_condition", models.CharField(blank=True, max_length=50)),
                ("special_event", models.CharField(blank=True, max_length=200)),
                ("historical_days_used", models.IntegerField(default=90)),
                (
                    "trend_direction",
                    models.CharField(
                        choices=[
                            ("increasing", "Increasing"),
                            ("stable", "Stable"),
                            ("decreasing", "Decreasing"),
                        ],
                        default="stable",
                        max_length=20,
                    ),
                ),
                ("model_version", models.CharField(default="v1.0", max_length=50)),
                (
                    "model_type",
                    models.CharField(
                        default="lstm",
                        help_text="Model type: lstm, arima, prophet, etc.",
                        max_length=50,
                    ),
                ),
                ("actual_order_count", models.IntegerField(blank=True, null=True)),
                (
                    "actual_revenue",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "prediction_error",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Absolute percentage error",
                        max_digits=10,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "partner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="demand_forecasts",
                        to="partners.partner",
                    ),
                ),
            ],
            options={
                "verbose_name": "Demand Forecast",
                "verbose_name_plural": "Demand Forecasts",
                "db_table": "demand_forecasts",
                "ordering": ["-forecast_date", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["forecast_date", "granularity"],
                        name="demand_fore_forecas_0e5241_idx",
                    ),
                    models.Index(
                        fields=["partner", "forecast_date"],
                        name="demand_fore_partner_bcfaf1_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="demand_fore_created_1e8f46_idx"
                    ),
                ],
                "unique_together": {
                    ("forecast_date", "forecast_hour", "partner", "granularity")
                },
            },
        ),
        migrations.CreateModel(
            name="FraudDetection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "risk_score",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Overall risk score (0-100)",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("low", "Low Risk"),
                            ("medium", "Medium Risk"),
                            ("high", "High Risk"),
                            ("critical", "Critical Risk"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "fraud_indicators",
                    models.JSONField(
                        default=list, help_text="List of detected fraud indicators"
                    ),
                ),
                (
                    "velocity_score",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Transaction velocity anomaly score",
                        max_digits=5,
                    ),
                ),
                (
                    "pattern_score",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Behavioral pattern anomaly score",
                        max_digits=5,
                    ),
                ),
                (
                    "device_score",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Device fingerprint anomaly score",
                        max_digits=5,
                    ),
                ),
                (
                    "location_score",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Location anomaly score",
                        max_digits=5,
                    ),
                ),
                ("is_velocity_anomaly", models.BooleanField(default=False)),
                ("is_pattern_anomaly", models.BooleanField(default=False)),
                ("is_device_mismatch", models.BooleanField(default=False)),
                ("is_location_anomaly", models.BooleanField(default=False)),
                ("is_payment_anomaly", models.BooleanField(default=False)),
                ("user_age_days", models.IntegerField(help_text="Account age in days")),
                ("order_count_24h", models.IntegerField(default=0)),
                ("order_count_7d", models.IntegerField(default=0)),
                ("failed_payment_count", models.IntegerField(default=0)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("device_fingerprint", models.CharField(blank=True, max_length=255)),
                ("user_agent", models.TextField(blank=True)),
                (
                    "recommended_action",
                    models.CharField(
                        choices=[
                            ("approve", "Approve"),
                            ("review", "Manual Review"),
                            ("decline", "Decline"),
                            ("block_user", "Block User"),
                        ],
                        default="review",
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("reviewing", "Under Review"),
                            ("approved", "Approved - Not Fraud"),
                            ("blocked", "Blocked - Fraud Detected"),
                            ("false_positive", "False Positive"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("resolution_notes", models.TextField(blank=True)),
                ("model_version", models.CharField(default="v1.0", max_length=50)),
                ("detection_rules", models.JSONField(blank=True, default=list)),
                ("auto_action_taken", models.CharField(blank=True, max_length=50)),
                ("action_taken_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fraud_detections",
                        to="orders.order",
                    ),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fraud_detections",
                        to="payments.payment",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_fraud_cases",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fraud_detections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Fraud Detection",
                "verbose_name_plural": "Fraud Detections",
                "db_table": "fraud_detections",
                "ordering": ["-risk_score", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="fraud_detec_user_id_4905a4_idx",
                    ),
                    models.Index(
                        fields=["order", "-created_at"],
                        name="fraud_detec_order_i_c68840_idx",
                    ),
                    models.Index(
                        fields=["risk_level", "status"],
                        name="fraud_detec_risk_le_4eda15_idx",
                    ),
                    models.Index(
                        fields=["status", "-created_at"],
                        name="fraud_detec_status_62bff5_idx",
                    ),
                    models.Index(
                        fields=["-risk_score", "-created_at"],
                        name="fraud_detec_risk_sc_f911a8_idx",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="garmentrecognition",
            index=models.Index(
                fields=["user", "-created_at"], name="garment_rec_user_id_8ea1d7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="garmentrecognition",
            index=models.Index(
                fields=["order", "-created_at"], name="garment_rec_order_i_704324_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="garmentrecognition",
            index=models.Index(
                fields=["garment_type", "-created_at"],
                name="garment_rec_garment_60812d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="garmentrecognition",
            index=models.Index(
                fields=["confidence_level"], name="garment_rec_confide_4ea2dc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="mlmodel",
            index=models.Index(
                fields=["model_type", "status"], name="ml_models_model_t_426c2a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="mlmodel",
            index=models.Index(fields=["version"], name="ml_models_version_ad88fc_idx"),
        ),
        migrations.AddIndex(
            model_name="mlmodel",
            index=models.Index(
                fields=["-created_at"], name="ml_models_created_a85554_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="priceestimation",
            index=models.Index(
                fields=["service", "-created_at"], name="price_estim_service_b85198_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="priceestimation",
            index=models.Index(
                fields=["garment_type", "service_type"],
                name="price_estim_garment_38fbf2_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="priceestimation",
            index=models.Index(
                fields=["created_at"], name="price_estim_created_df1313_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="recommendation",
            index=models.Index(
                fields=["user", "-created_at"], name="ai_recommen_user_id_4b41b8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="recommendation",
            index=models.Index(
                fields=["order", "-relevance_score"],
                name="ai_recommen_order_i_f2ecbf_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="recommendation",
            index=models.Index(
                fields=["recommendation_type", "-relevance_score"],
                name="ai_recommen_recomme_6525cb_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="recommendation",
            index=models.Index(
                fields=["was_shown", "was_accepted"],
                name="ai_recommen_was_sho_23e849_idx",
            ),
        ),
    ]
