# Generated by Django 6.0 on 2026-01-03 10:58

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("orders", "0001_initial"),
        ("partners", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LocationUpdate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "latitude",
                    models.DecimalField(
                        decimal_places=6,
                        help_text="GPS latitude (-90 to 90)",
                        max_digits=9,
                        validators=[
                            django.core.validators.MinValueValidator(-90),
                            django.core.validators.MaxValueValidator(90),
                        ],
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        decimal_places=6,
                        help_text="GPS longitude (-180 to 180)",
                        max_digits=9,
                        validators=[
                            django.core.validators.MinValueValidator(-180),
                            django.core.validators.MaxValueValidator(180),
                        ],
                    ),
                ),
                (
                    "accuracy",
                    models.FloatField(
                        blank=True, help_text="GPS accuracy in meters", null=True
                    ),
                ),
                (
                    "altitude",
                    models.FloatField(
                        blank=True, help_text="Altitude in meters", null=True
                    ),
                ),
                (
                    "speed",
                    models.FloatField(blank=True, help_text="Speed in km/h", null=True),
                ),
                (
                    "heading",
                    models.FloatField(
                        blank=True,
                        help_text="Direction in degrees (0-360)",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(360),
                        ],
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True, help_text="Reverse geocoded address", max_length=500
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("idle", "Idle"),
                            ("picking_up", "Picking Up"),
                            ("in_transit", "In Transit"),
                            ("delivering", "Delivering"),
                            ("completed", "Completed"),
                        ],
                        default="idle",
                        help_text="Current delivery status",
                        max_length=50,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional tracking data (battery, network, etc.)",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="When location was captured",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        help_text="Order being tracked",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="location_updates",
                        to="orders.order",
                    ),
                ),
                (
                    "partner",
                    models.ForeignKey(
                        help_text="Partner delivering the order",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="location_updates",
                        to="partners.partner",
                    ),
                ),
            ],
            options={
                "verbose_name": "Location Update",
                "verbose_name_plural": "Location Updates",
                "db_table": "location_updates",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["order", "-timestamp"],
                        name="location_up_order_i_7d08a8_idx",
                    ),
                    models.Index(
                        fields=["partner", "-timestamp"],
                        name="location_up_partner_cb95a3_idx",
                    ),
                    models.Index(
                        fields=["status"], name="location_up_status_02af64_idx"
                    ),
                    models.Index(
                        fields=["timestamp"], name="location_up_timesta_371544_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Route",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "origin_latitude",
                    models.DecimalField(
                        decimal_places=6,
                        help_text="Starting point latitude",
                        max_digits=9,
                    ),
                ),
                (
                    "origin_longitude",
                    models.DecimalField(
                        decimal_places=6,
                        help_text="Starting point longitude",
                        max_digits=9,
                    ),
                ),
                (
                    "origin_address",
                    models.CharField(help_text="Starting address", max_length=500),
                ),
                (
                    "destination_latitude",
                    models.DecimalField(
                        decimal_places=6, help_text="Destination latitude", max_digits=9
                    ),
                ),
                (
                    "destination_longitude",
                    models.DecimalField(
                        decimal_places=6,
                        help_text="Destination longitude",
                        max_digits=9,
                    ),
                ),
                (
                    "destination_address",
                    models.CharField(help_text="Destination address", max_length=500),
                ),
                (
                    "waypoints",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Intermediate waypoints [(lat, lon), ...]",
                    ),
                ),
                (
                    "encoded_polyline",
                    models.TextField(
                        blank=True, help_text="Encoded polyline from Google Maps"
                    ),
                ),
                (
                    "distance_meters",
                    models.IntegerField(
                        blank=True,
                        help_text="Total route distance in meters",
                        null=True,
                    ),
                ),
                (
                    "duration_seconds",
                    models.IntegerField(
                        blank=True, help_text="Estimated duration in seconds", null=True
                    ),
                ),
                (
                    "estimated_arrival",
                    models.DateTimeField(
                        blank=True, help_text="Estimated arrival time", null=True
                    ),
                ),
                (
                    "actual_arrival",
                    models.DateTimeField(
                        blank=True, help_text="Actual arrival time", null=True
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When partner started the route",
                        null=True,
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, help_text="When route was completed", null=True
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether route is currently active"
                    ),
                ),
                (
                    "order",
                    models.OneToOneField(
                        help_text="Order for this route",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="route",
                        to="orders.order",
                    ),
                ),
                (
                    "partner",
                    models.ForeignKey(
                        help_text="Partner assigned to this route",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="routes",
                        to="partners.partner",
                    ),
                ),
            ],
            options={
                "verbose_name": "Route",
                "verbose_name_plural": "Routes",
                "db_table": "routes",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["order"], name="routes_order_i_578a64_idx"),
                    models.Index(
                        fields=["partner", "-created_at"],
                        name="routes_partner_858f55_idx",
                    ),
                    models.Index(
                        fields=["is_active"], name="routes_is_acti_9ece4b_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="TrackingSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "started_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When tracking started"
                    ),
                ),
                (
                    "ended_at",
                    models.DateTimeField(
                        blank=True, help_text="When tracking ended", null=True
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether session is active"
                    ),
                ),
                (
                    "total_distance_meters",
                    models.FloatField(
                        default=0, help_text="Total distance covered in meters"
                    ),
                ),
                (
                    "total_duration_seconds",
                    models.IntegerField(
                        default=0, help_text="Total duration in seconds"
                    ),
                ),
                (
                    "average_speed_kmh",
                    models.FloatField(default=0, help_text="Average speed in km/h"),
                ),
                (
                    "order",
                    models.ForeignKey(
                        help_text="Order being tracked",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tracking_sessions",
                        to="orders.order",
                    ),
                ),
                (
                    "partner",
                    models.ForeignKey(
                        help_text="Partner being tracked",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tracking_sessions",
                        to="partners.partner",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tracking Session",
                "verbose_name_plural": "Tracking Sessions",
                "db_table": "tracking_sessions",
                "ordering": ["-started_at"],
                "indexes": [
                    models.Index(
                        fields=["order", "-started_at"],
                        name="tracking_se_order_i_71f937_idx",
                    ),
                    models.Index(
                        fields=["partner", "-started_at"],
                        name="tracking_se_partner_83f50c_idx",
                    ),
                    models.Index(
                        fields=["is_active"], name="tracking_se_is_acti_da1d9b_idx"
                    ),
                ],
            },
        ),
    ]
