# Generated by Django 6.0 on 2026-01-03 15:00

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("partners", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AnalyticsCache",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "cache_key",
                    models.CharField(db_index=True, max_length=255, unique=True),
                ),
                (
                    "cache_type",
                    models.CharField(
                        choices=[
                            ("dashboard", "Dashboard Metrics"),
                            ("revenue", "Revenue Analytics"),
                            ("orders", "Order Analytics"),
                            ("partners", "Partner Analytics"),
                            ("customers", "Customer Analytics"),
                        ],
                        max_length=50,
                    ),
                ),
                ("data", models.JSONField()),
                ("expires_at", models.DateTimeField(db_index=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Analytics Cache",
                "verbose_name_plural": "Analytics Cache",
                "db_table": "analytics_cache",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["cache_key", "expires_at"],
                        name="analytics_c_cache_k_afe5b0_idx",
                    ),
                    models.Index(
                        fields=["cache_type", "expires_at"],
                        name="analytics_c_cache_t_3743ea_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="DailyRevenueSummary",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateField(db_index=True, unique=True)),
                (
                    "total_revenue",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                ("order_count", models.IntegerField(default=0)),
                (
                    "average_order_value",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "cash_revenue",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "card_revenue",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "wallet_revenue",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "online_revenue",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                ("completed_orders", models.IntegerField(default=0)),
                ("cancelled_orders", models.IntegerField(default=0)),
                ("pending_orders", models.IntegerField(default=0)),
                ("new_customers", models.IntegerField(default=0)),
                ("returning_customers", models.IntegerField(default=0)),
                (
                    "refund_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                ("refund_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Daily Revenue Summary",
                "verbose_name_plural": "Daily Revenue Summaries",
                "db_table": "daily_revenue_summaries",
                "ordering": ["-date"],
                "indexes": [
                    models.Index(fields=["-date"], name="daily_reven_date_1c3101_idx"),
                    models.Index(
                        fields=["date", "total_revenue"],
                        name="daily_reven_date_4cad14_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="CustomerAnalytics",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("total_orders", models.IntegerField(default=0)),
                ("completed_orders", models.IntegerField(default=0)),
                ("cancelled_orders", models.IntegerField(default=0)),
                (
                    "total_spent",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "average_order_value",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "lifetime_value",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                ("first_order_date", models.DateTimeField(blank=True, null=True)),
                ("last_order_date", models.DateTimeField(blank=True, null=True)),
                ("days_since_last_order", models.IntegerField(blank=True, null=True)),
                (
                    "order_frequency_days",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "customer_segment",
                    models.CharField(
                        choices=[
                            ("new", "New Customer"),
                            ("occasional", "Occasional Customer"),
                            ("regular", "Regular Customer"),
                            ("vip", "VIP Customer"),
                            ("churned", "Churned Customer"),
                        ],
                        default="new",
                        max_length=20,
                    ),
                ),
                (
                    "favorite_service_category",
                    models.CharField(blank=True, max_length=50),
                ),
                (
                    "preferred_payment_method",
                    models.CharField(blank=True, max_length=20),
                ),
                (
                    "avg_rating_given",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=3,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00")),
                            django.core.validators.MaxValueValidator(Decimal("5.00")),
                        ],
                    ),
                ),
                (
                    "churn_risk_score",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00")),
                            django.core.validators.MaxValueValidator(Decimal("100.00")),
                        ],
                    ),
                ),
                ("is_at_churn_risk", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analytics",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Customer Analytics",
                "verbose_name_plural": "Customer Analytics",
                "db_table": "customer_analytics",
                "ordering": ["-lifetime_value"],
                "indexes": [
                    models.Index(
                        fields=["-lifetime_value"],
                        name="customer_an_lifetim_f4afb7_idx",
                    ),
                    models.Index(
                        fields=["customer_segment"],
                        name="customer_an_custome_2e6f3c_idx",
                    ),
                    models.Index(
                        fields=["-last_order_date"],
                        name="customer_an_last_or_7cb627_idx",
                    ),
                    models.Index(
                        fields=["is_at_churn_risk"],
                        name="customer_an_is_at_c_cf9389_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="PartnerPerformanceMetric",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                ("orders_received", models.IntegerField(default=0)),
                ("orders_accepted", models.IntegerField(default=0)),
                ("orders_rejected", models.IntegerField(default=0)),
                ("orders_completed", models.IntegerField(default=0)),
                ("orders_cancelled", models.IntegerField(default=0)),
                (
                    "total_revenue",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                ("avg_acceptance_time", models.IntegerField(blank=True, null=True)),
                ("avg_pickup_time", models.IntegerField(blank=True, null=True)),
                ("avg_processing_time", models.IntegerField(blank=True, null=True)),
                ("avg_delivery_time", models.IntegerField(blank=True, null=True)),
                ("avg_total_time", models.IntegerField(blank=True, null=True)),
                (
                    "avg_rating",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=3,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00")),
                            django.core.validators.MaxValueValidator(Decimal("5.00")),
                        ],
                    ),
                ),
                ("rating_count", models.IntegerField(default=0)),
                ("issues_reported", models.IntegerField(default=0)),
                ("items_damaged", models.IntegerField(default=0)),
                ("items_lost", models.IntegerField(default=0)),
                (
                    "capacity_utilized_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00")),
                            django.core.validators.MaxValueValidator(Decimal("100.00")),
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "partner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analytics_performance_metrics",
                        to="partners.partner",
                    ),
                ),
            ],
            options={
                "verbose_name": "Partner Performance Metric",
                "verbose_name_plural": "Partner Performance Metrics",
                "db_table": "partner_performance_metrics",
                "ordering": ["-date", "partner"],
                "indexes": [
                    models.Index(
                        fields=["partner", "-date"],
                        name="partner_per_partner_7e6d6b_idx",
                    ),
                    models.Index(fields=["-date"], name="partner_per_date_d4c5ac_idx"),
                    models.Index(
                        fields=["partner", "avg_rating"],
                        name="partner_per_partner_2aa0c7_idx",
                    ),
                ],
                "unique_together": {("partner", "date")},
            },
        ),
        migrations.CreateModel(
            name="ReportSchedule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("revenue", "Revenue Report"),
                            ("orders", "Orders Report"),
                            ("partners", "Partner Performance Report"),
                            ("customers", "Customer Analytics Report"),
                            ("inventory", "Inventory Report"),
                            ("custom", "Custom Report"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                            ("quarterly", "Quarterly"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "day_of_week",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(6),
                        ],
                    ),
                ),
                (
                    "day_of_month",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(31),
                        ],
                    ),
                ),
                ("time_of_day", models.TimeField(default="09:00:00")),
                ("email_to", models.JSONField(default=list)),
                (
                    "format",
                    models.CharField(
                        choices=[("pdf", "PDF"), ("excel", "Excel"), ("csv", "CSV")],
                        default="pdf",
                        max_length=10,
                    ),
                ),
                ("filters", models.JSONField(blank=True, default=dict)),
                ("is_active", models.BooleanField(default=True)),
                ("last_run_at", models.DateTimeField(blank=True, null=True)),
                ("next_run_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scheduled_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Report Schedule",
                "verbose_name_plural": "Report Schedules",
                "db_table": "report_schedules",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["is_active", "next_run_at"],
                        name="report_sche_is_acti_1056cd_idx",
                    ),
                    models.Index(
                        fields=["created_by"], name="report_sche_created_5e3dad_idx"
                    ),
                ],
            },
        ),
    ]
