# Generated by Django 6.0 on 2026-01-02 13:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("orders", "0001_initial"),
        ("payments", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationPreference",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="notification_preferences",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "order_updates_email",
                    models.BooleanField(
                        default=True, help_text="Receive order status updates via email"
                    ),
                ),
                (
                    "order_updates_push",
                    models.BooleanField(
                        default=True,
                        help_text="Receive order status updates as push notifications",
                    ),
                ),
                (
                    "payment_updates_email",
                    models.BooleanField(
                        default=True,
                        help_text="Receive payment confirmations via email",
                    ),
                ),
                (
                    "payment_updates_push",
                    models.BooleanField(
                        default=True,
                        help_text="Receive payment updates as push notifications",
                    ),
                ),
                (
                    "refund_updates_email",
                    models.BooleanField(
                        default=True, help_text="Receive refund updates via email"
                    ),
                ),
                (
                    "refund_updates_push",
                    models.BooleanField(
                        default=True,
                        help_text="Receive refund updates as push notifications",
                    ),
                ),
                (
                    "partner_updates_email",
                    models.BooleanField(
                        default=True,
                        help_text="Receive partner-related updates via email",
                    ),
                ),
                (
                    "partner_updates_push",
                    models.BooleanField(
                        default=True,
                        help_text="Receive partner updates as push notifications",
                    ),
                ),
                (
                    "marketing_emails",
                    models.BooleanField(
                        default=False,
                        help_text="Receive marketing and promotional emails",
                    ),
                ),
                (
                    "promotional_push",
                    models.BooleanField(
                        default=False,
                        help_text="Receive promotional push notifications",
                    ),
                ),
                (
                    "account_updates_email",
                    models.BooleanField(
                        default=True,
                        help_text="Receive account-related updates via email",
                    ),
                ),
                (
                    "order_updates_sms",
                    models.BooleanField(
                        default=False, help_text="Receive order updates via SMS"
                    ),
                ),
                (
                    "payment_updates_sms",
                    models.BooleanField(
                        default=False, help_text="Receive payment updates via SMS"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Notification Preference",
                "verbose_name_plural": "Notification Preferences",
            },
        ),
        migrations.CreateModel(
            name="NotificationTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        db_index=True,
                        help_text="Notification type this template is for",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Human-readable template name", max_length=255
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Description of when this template is used",
                    ),
                ),
                (
                    "email_subject",
                    models.CharField(
                        help_text="Email subject line. Can use {{ variables }}",
                        max_length=255,
                    ),
                ),
                (
                    "email_body_html",
                    models.TextField(
                        help_text="HTML email body. Can use {{ variables }}"
                    ),
                ),
                (
                    "email_body_text",
                    models.TextField(
                        help_text="Plain text email body. Can use {{ variables }}"
                    ),
                ),
                (
                    "title_template",
                    models.CharField(
                        help_text="Notification title template. Can use {{ variables }}",
                        max_length=255,
                    ),
                ),
                (
                    "message_template",
                    models.TextField(
                        help_text="Notification message template. Can use {{ variables }}"
                    ),
                ),
                (
                    "sms_template",
                    models.CharField(
                        blank=True,
                        help_text="SMS message template (max 160 chars). Can use {{ variables }}",
                        max_length=160,
                    ),
                ),
                (
                    "action_url_template",
                    models.CharField(
                        blank=True,
                        help_text="URL template for notification action. Can use {{ variables }}",
                        max_length=500,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this template is currently in use",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Notification Template",
                "verbose_name_plural": "Notification Templates",
                "ordering": ["type"],
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "notification_id",
                    models.CharField(
                        db_index=True,
                        editable=False,
                        help_text="Auto-generated notification ID",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("order_created", "Order Created"),
                            ("order_confirmed", "Order Confirmed"),
                            ("order_picked_up", "Order Picked Up"),
                            ("order_in_progress", "Order In Progress"),
                            ("order_ready", "Order Ready for Delivery"),
                            ("order_out_for_delivery", "Order Out for Delivery"),
                            ("order_delivered", "Order Delivered"),
                            ("order_cancelled", "Order Cancelled"),
                            ("payment_initiated", "Payment Initiated"),
                            ("payment_completed", "Payment Completed"),
                            ("payment_failed", "Payment Failed"),
                            ("payment_refunded", "Payment Refunded"),
                            ("refund_requested", "Refund Requested"),
                            ("refund_processing", "Refund Processing"),
                            ("refund_completed", "Refund Completed"),
                            ("refund_failed", "Refund Failed"),
                            ("partner_assigned", "Partner Assigned to Order"),
                            ("partner_approved", "Partner Account Approved"),
                            ("new_order_assigned", "New Order Assigned"),
                            ("welcome", "Welcome to LaundryConnect"),
                            ("account_verified", "Account Verified"),
                            ("password_changed", "Password Changed"),
                            ("general", "General Notification"),
                            ("promotion", "Promotional Notification"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("message", models.TextField()),
                (
                    "is_read",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Whether the notification has been read",
                    ),
                ),
                (
                    "read_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the notification was marked as read",
                        null=True,
                    ),
                ),
                (
                    "email_sent",
                    models.BooleanField(
                        default=False, help_text="Whether email notification was sent"
                    ),
                ),
                (
                    "email_sent_at",
                    models.DateTimeField(
                        blank=True, help_text="When the email was sent", null=True
                    ),
                ),
                (
                    "email_error",
                    models.TextField(
                        blank=True, help_text="Email sending error message if any"
                    ),
                ),
                (
                    "action_url",
                    models.CharField(
                        blank=True,
                        help_text="Deep link or action URL for the notification",
                        max_length=500,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional metadata for the notification",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notifications",
                        to="orders.order",
                    ),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notifications",
                        to="payments.payment",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification",
                "verbose_name_plural": "Notifications",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "is_read", "-created_at"],
                        name="notificatio_user_id_f2ad08_idx",
                    ),
                    models.Index(
                        fields=["user", "type", "-created_at"],
                        name="notificatio_user_id_3b3832_idx",
                    ),
                ],
            },
        ),
    ]
