# Generated by Django 6.0 on 2026-01-03 10:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PushSubscription",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "endpoint",
                    models.URLField(
                        help_text="Push service endpoint URL", max_length=500
                    ),
                ),
                (
                    "p256dh_key",
                    models.CharField(
                        help_text="P256DH public key for encryption", max_length=255
                    ),
                ),
                (
                    "auth_key",
                    models.CharField(
                        help_text="Auth secret for encryption", max_length=255
                    ),
                ),
                (
                    "device_name",
                    models.CharField(
                        blank=True,
                        help_text='Device/browser name (e.g., "Chrome on MacBook")',
                        max_length=100,
                    ),
                ),
                (
                    "user_agent",
                    models.CharField(
                        blank=True,
                        help_text="Browser user agent string",
                        max_length=500,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Whether this subscription is active",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "last_used_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Last time a push was sent to this subscription",
                        null=True,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who owns this push subscription",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="push_subscriptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Push Subscription",
                "verbose_name_plural": "Push Subscriptions",
                "db_table": "push_subscriptions",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "is_active"],
                        name="push_subscr_user_id_c81a15_idx",
                    ),
                    models.Index(
                        fields=["endpoint"], name="push_subscr_endpoin_48e896_idx"
                    ),
                ],
                "unique_together": {("user", "endpoint")},
            },
        ),
    ]
