# Generated by Django 6.0 on 2026-01-03 10:10

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("orders", "0001_initial"),
        ("partners", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatRoom",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "room_id",
                    models.CharField(
                        db_index=True,
                        help_text="Unique identifier for the chat room (e.g., CHAT20260103ABC12345)",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether the chat room is active"
                    ),
                ),
                (
                    "last_message_at",
                    models.DateTimeField(
                        blank=True, help_text="Timestamp of the last message", null=True
                    ),
                ),
                (
                    "customer_unread_count",
                    models.IntegerField(
                        default=0, help_text="Number of unread messages for customer"
                    ),
                ),
                (
                    "partner_unread_count",
                    models.IntegerField(
                        default=0, help_text="Number of unread messages for partner"
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        help_text="Customer in this chat",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customer_chat_rooms",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "order",
                    models.OneToOneField(
                        help_text="Order associated with this chat room",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_room",
                        to="orders.order",
                    ),
                ),
                (
                    "partner",
                    models.ForeignKey(
                        help_text="Partner in this chat",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="partner_chat_rooms",
                        to="partners.partner",
                    ),
                ),
            ],
            options={
                "verbose_name": "Chat Room",
                "verbose_name_plural": "Chat Rooms",
                "db_table": "chat_rooms",
                "ordering": ["-last_message_at", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "message_type",
                    models.CharField(
                        choices=[
                            ("text", "Text Message"),
                            ("image", "Image"),
                            ("file", "File Attachment"),
                            ("location", "Location Share"),
                            ("system", "System Message"),
                        ],
                        default="text",
                        help_text="Type of message",
                        max_length=20,
                    ),
                ),
                (
                    "content",
                    models.TextField(help_text="Message content (text or file URL)"),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        help_text="Uploaded file (for image/file messages)",
                        null=True,
                        upload_to="chat/files/%Y/%m/%d/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=[
                                    "jpg",
                                    "jpeg",
                                    "png",
                                    "gif",
                                    "pdf",
                                    "doc",
                                    "docx",
                                    "txt",
                                ]
                            )
                        ],
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional data (location coordinates, file info, etc.)",
                    ),
                ),
                (
                    "is_read",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the message has been read by recipient",
                    ),
                ),
                (
                    "read_at",
                    models.DateTimeField(
                        blank=True, help_text="When the message was read", null=True
                    ),
                ),
                (
                    "is_delivered",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the message was delivered to recipient",
                    ),
                ),
                (
                    "delivered_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the message was delivered",
                        null=True,
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        help_text="User who sent the message",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        help_text="Chat room this message belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="chat.chatroom",
                    ),
                ),
            ],
            options={
                "verbose_name": "Chat Message",
                "verbose_name_plural": "Chat Messages",
                "db_table": "chat_messages",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="TypingIndicator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now=True)),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="typing_indicators",
                        to="chat.chatroom",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="typing_in_rooms",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Typing Indicator",
                "verbose_name_plural": "Typing Indicators",
                "db_table": "chat_typing_indicators",
            },
        ),
        migrations.AddIndex(
            model_name="chatroom",
            index=models.Index(
                fields=["customer", "-last_message_at"],
                name="chat_rooms_custome_9903a4_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="chatroom",
            index=models.Index(
                fields=["partner", "-last_message_at"],
                name="chat_rooms_partner_8f5ce1_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="chatroom",
            index=models.Index(fields=["order"], name="chat_rooms_order_i_d7c7d6_idx"),
        ),
        migrations.AddIndex(
            model_name="chatmessage",
            index=models.Index(
                fields=["room", "created_at"], name="chat_messag_room_id_cc7f0e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chatmessage",
            index=models.Index(
                fields=["room", "is_read"], name="chat_messag_room_id_fc300c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chatmessage",
            index=models.Index(
                fields=["sender", "-created_at"], name="chat_messag_sender__5f8b49_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="typingindicator",
            unique_together={("room", "user")},
        ),
    ]
